version: "2"

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - goconst
    - misspell
    - unparam
    - nakedret
    - prealloc
    - revive
    - bodyclose
    - whitespace
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - lostcancel
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    unparam:
      check-exported: false
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
    revive:
      rules:
        - name: var-naming
          arguments:
            - []
            - []
            - - skip-package-name-checks: true

  exclusions:
    paths:
      - ".*/fakes.go"


issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true

run:
  tests: false
